title: shuang's dump
# author: shuang
email: zoecsh@hotmail.com
description: >- # this means to ignore newlines until "baseurl:"
  dump is usually referring to a site for depositing garbage. i don't think things here are garbage, but maybe they are. maybe this dump is different.

baseurl: "/dump" # the subpath of your site, e.g. /blog
codeurl: "https://github.com/owochel/dump/tree/main"
asseturl: "https://raw.githubusercontent.com/owochel/dump/main"
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username: owochel

# Build settings
# theme: minima
# theme: jekyll-theme-slate
remote_theme: b2a3e8/jekyll-theme-console
# remote_theme: b2a3e8/jekyll-theme-console
plugins:
  - jekyll-feed

header_pages:
  - index.md
  - about.md

markdown: kramdown

collections:
  weekly:
    output: true
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
